### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kianoofficial** [MrDadosz/GangWars#2]
nie moge przejmowac terenow chociaz dobrze podpiolem pod baze

**Comment by MrDadosz** [comment]
Aby skrypt poprawnie działał wymagany jest plik licencyjny. Na GitHubie można podejrzeć jakie są możliwości skryptu, ustawienia edycji i zewnętrzne funkcje umożliwiające podłączenie pod inny gamemode.  Kod na GitHubie nie zawiera kodu z pliku licencyjnego.
